version: '3'
services:
  apache1:
        container_name: apache1
        build: ./apache1
        ports: 
          - 6060:80
  apache2:
        container_name: apache2
        build: ./apache2
        ports: 
          - 7070:80        
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 50M
            reservations:
              cpus: '0.25'
              memory: 20M
  haproxy_img:
        container_name: haproxy
        build: ./haproxy
        ports: 
          - 80:80       
